### ISSUE TITLE
ERROR:  While Building the package.

### ISSUE THREAD

**Issue by shrikant-lahase** [fuxey/Linux-System-Monitoring-Library#10]
Hi,

I am trying to build the package as per instructions given in readme.
ERROR:
```
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at tests/CMakeLists.txt:6 (add_subdirectory):
  The source directory

    /home/sathvik/Downloads/sys_monitor/Linux-System-Monitoring-Library-master/thirdparty/Catch2

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:50 (include)


-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring incomplete, errors occurred!```

**Comment by fuxey** [comment]
Hi, 

this error occurs because, it requires the submodules. 
for now you can download the submodules via: 
`git submodule update --init --recursive `

i will fix the cmake file in order that no sublibs are required for the lib.

**Comment by shrikant-lahase** [comment]
Thanks for the reply.

**Comment by cesto93** [comment]
> i will fix the cmake file in order that no sublibs are required for the lib.

Hi I'm interested in using the lib without third-part dependency . 
If you want i can make a modify on CMakeLists.txt adding an option for disabling third-part dependency, compiling without options will produce the same result of the original cmake file.
Something like this:
[CMakeLists.txt](https://github.com/fuxey/Linux-System-Monitoring-Library/files/6891516/CMakeLists.txt)
If you like that i can make a pull request, or i can modify the patch.

**Comment by fuxey** [comment]
Hi @cesto93 , 

the libs are used for the examples, except the simple monitor. 
a Flag for excluding would be awesome! 
rename the flag to USE_EXAMPLES or something similar and exclude also the examples except simple monitor. 
thanks!

**Comment by fuxey** [comment]
see my latest commit where I introduced the USE_THIRDPARTY_EXAMPLES CMake Option.
