### ISSUE TITLE
Not working without Timer

### ISSUE THREAD

**Issue by hofin34** [fuxey/Linux-System-Monitoring-Library#14]
I would like to use your library just once to get some info, but when I use this code:
```
//.. includes
int main(){
    auto processes = std::make_unique<linuxProcessLoad>();
    auto cpuMonitoring = std::make_unique<cpuLoad>("/proc/stat");
    cpuMonitoring->initCpuUsage();
    double usage = cpuMonitoring->getCurrentCpuUsage();
    return 0;
}
```
program crashes on line with `geCurrentCpuUsage()` with exception:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
```

But when is used this in your Timer class as the example, it works fine

**Comment by fuxey** [comment]
@hofin34 , 
Thank you for finding and reporting this Issue! it's indeed a bug in the initialization! should now be fixed!
